quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Amadeus": [0.3, 0.6]
    "Sabre": [0.45, 0.23]
    "Travelport": [0.57, 0.69]
    "KAYAK": [0.78, 0.34]
    "Expedia": [0.40, 0.34]
    "Priceline": [0.35, 0.78]
    "Orbitz": [0.25, 0.5]
    "Our Target Product": [0.7, 0.8]
